config/routes.rb
AmericanTelecomWest::Application.routes.draw do
  
  devise_for :users
  root :to => 'static_pages#home'

  resources :cabling_services
  resources :nortel_services
  resources :cabling_add_servs
  resources :nortel_add_servs
  resources :addons
  resources :clients
  resources :faqs

  get '/admin' => 'static_pages#admin'
  get '/tmetrics' => 'static_pages#tmetrics'
  
end

app/models/addon.rb
class Addon < ActiveRecord::Base
  
end

app/models/cabling_add_serv.rb
class CablingAddServ < ActiveRecord::Base
end

app/models/cabling_service.rb
class CablingService < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base
  
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  
end

app/models/nortel_add_serv.rb
class NortelAddServ < ActiveRecord::Base
end

app/models/nortel_service.rb
class NortelService < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/addons_controller.rb
class AddonsController < ApplicationController
  before_filter :is_admin?, except: [:index]
  
  def new
    @addon = Addon.new
  end

  def create
    @addon = Addon.create!(addon_params)
    redirect_to admin_path
  end

  def edit
    @addon = Addon.find(params[:id])
  end

  def update
    @addon = Addon.find(params[:id])
    if @addon.update_attributes(addon_params)
      redirect_to admin_path
    else
      render :edit
    end
  end

  def destroy
    Addon.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to admin_path }
      format.js
    end
  end

  private

  def addon_params
    params.require(:addon).permit(:nortel_intro, :nortel_conclusion, :cabling_intro, :cabling_conclusion)
  end

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected 
  def is_admin?
    if current_user && current_user.email == ENV["P_EMAIL"] || current_user && current_user.email == ENV["C_EMAIL"]
    else
      flash[:alert] = "Sorry. You do not have the correct administrative access to view the page you are trying to access."
      redirect_to root_path
    end
  end
end

app/controllers/cabling_add_servs_controller.rb
class CablingAddServsController < ApplicationController
  before_filter :is_admin?, except: [:index]
  
  def new
    @additional_service = CablingAddServ.new
  end

  def create
    @additional_service = CablingAddServ.create!(add_serv_params)
    redirect_to admin_path
  end

  def edit
    @additional_service = CablingAddServ.find(params[:id])
  end

  def update
    @additional_service = CablingAddServ.find(params[:id])
    if @additional_service.update_attributes(add_serv_params)
      redirect_to admin_path
    else
      render :edit
    end
  end

  def destroy
    cabling_add_serve = CablingAddServ.find(params[:id])
    cabling_add_serve.destroy
    respond_to do |format|
      format.html { redirect_to admin_path }
      format.js
    end
  end

  private

  def add_serv_params
    params.require(:cabling_add_serv).permit(:description)
  end

end 

app/controllers/cabling_services_controller.rb
class CablingServicesController < ApplicationController
  before_filter :is_admin?, except: [:index]
  
  def index 
    @cabling_services = CablingService.all
    @additional_services = CablingAddServ.all
  end

  def new
    @cabling_service = CablingService.new
  end

  def create
    @cabling_service = CablingService.create!(cabling_service_params)
    redirect_to admin_path
  end

  def edit
    @cabling_service = CablingService.find(params[:id])
  end

  def update
    @cabling_service = CablingService.find(params[:id])
    if @cabling_service.update_attributes(cabling_service_params)
      redirect_to admin_path
    else
      render :edit
    end
  end

  def destroy
    cabling_service = CablingService.find(params[:id])
    cabling_service.destroy
    respond_to do |format|
      format.html { redirect_to admin_path }
      format.js
    end
  end

  private

  def cabling_service_params
    params.require(:cabling_service).permit(:description)
  end
end 

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :is_admin?, except: [:index]
  
  def index 
    @clients = Client.all
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.create!(client_params)
    redirect_to admin_path
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update_attributes(client_params)
      redirect_to admin_path
    else
      render :edit
    end
  end

  def destroy
    Client.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to admin_path }
      format.js
    end
  end

  private

  def client_params
    params.require(:client).permit(:name, :logo_url, :tag)
  end

end 

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_filter :is_admin?, except: [:index]
  
  def index 
    @faqs = Faq.all
  end

  def new
    @faq = Faq.new
  end

  def create
    @faq = Faq.create!(faq_params)
    redirect_to admin_path
  end

  def edit
    @faq = Faq.find(params[:id])
  end

  def update
    @faq = Faq.find(params[:id])
    if @faq.update_attributes(faq_params)
      redirect_to admin_path
    else
      render :edit
    end
  end

  def destroy
    Faq.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to admin_path }
      format.js
    end
  end

  private

  def faq_params
    params.require(:faq).permit(:question, :answer)
  end

end 

app/controllers/nortel_add_servs_controller.rb
class NortelAddServsController < ApplicationController
  before_filter :is_admin?, except: [:index]
  
  def new
    @nortel_add_serv = NortelAddServ.new
  end

  def create
    @nortel_add_serv = NortelAddServ.create!(add_serv_params)
    redirect_to admin_path
  end

  def edit
    @nortel_add_serv = NortelAddServ.find(params[:id])
  end

  def update
    @nortel_add_serv = NortelAddServ.find(params[:id])
    if @nortel_add_serv.update_attributes(add_serv_params)
      redirect_to admin_path
    else
      render :edit
    end
  end

  def destroy
    nortel_add_serv = NortelAddServ.find(params[:id])
    nortel_add_serv.destroy
    respond_to do |format|
      format.html { redirect_to admin_path }
      format.js
    end
  end

  private

  def add_serv_params
    params.require(:nortel_add_serv).permit(:description)
  end

end 

app/controllers/nortel_services_controller.rb
class NortelServicesController < ApplicationController
  before_filter :is_admin?, except: [:index]
  
  def index 
    @nortel_services = NortelService.all
    @additional_services = NortelAddServ.all
  end

  def new
    @nortel_service = NortelService.new
  end

  def create
    @nortel_service = NortelService.create!(nortel_services_params)
    redirect_to admin_path
  end

  def edit
    @nortel_service = NortelService.find(params[:id])
  end

  def update
    @nortel_service = NortelService.find(params[:id])
    if @nortel_service.update_attributes(nortel_services_params)
      redirect_to admin_path
    else
      render :edit
    end
  end

  def destroy
    nortel_service = NortelService.find(params[:id])
    nortel_service.destroy
    respond_to do |format|
      format.html { redirect_to admin_path }
      format.js
    end
  end

  private

  def nortel_services_params
    params.require(:nortel_service).permit(:description)
  end
end 

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :is_admin?, only: [:admin]
  
  def home
  end

  def tmetrics
  end

  def nortel
  end

  def structuredcabling
  end

  def admin
    @faqs = Faq.all
    @nortel_services = NortelService.all
    @cabling_services = CablingService.all
    @nortel_add_servs = NortelAddServ.all
    @cabling_add_servs = CablingAddServ.all
    @addon = Addon.first
    @clients = Client.all
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper
  def cp(path)
    "active" if current_page?(path)
  end

  protected 
  def is_admin?
    current_user && current_user.email == ENV["P_EMAIL"] || current_user && current_user.email == ENV["C_EMAIL"]
  end
end

app/views/addons/_form.html.erb
<%= form_for @addon do |f| %>
<div class="form-inline">
  <div class="form-group col-xs-12">
    <%= f.label :nortel_intro %><br>
    <%= f.text_area :nortel_intro, :size => "30x6", class: "form-control" %>
    <%= f.label :nortel_conclusion %><br>
    <%= f.text_area :nortel_conclusion, :size => "30x6", class: "form-control" %>
    <%= f.label :cabling_intro %><br>
    <%= f.text_area :cabling_intro, :size => "30x6", class: "form-control" %>
    <%= f.label :cabling_conclusion %><br>
    <%= f.text_area :cabling_conclusion, :size => "30x6", class: "form-control" %>
  </div>
</div>
<%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/addons/destroy.js.erb
$('.delete_link').bind('ajax:success', function(){
  $(this).closest('li').remove();
});

app/views/addons/edit.html.erb
<div class="container">

<h2>Edit Service Intros and Conclusions</h2>
<%= render 'form' %>
</div>

app/views/addons/new.html.erb
<div class="container">
<h2>Add Intro and Conclusion to Services</h2>

<%= render 'form' %>
</div>

app/views/cabling_add_serv/new.html.erb
<div class="container">
<h2>Add a New Additional Service</h2>

<%= render 'form' %>
</div>

app/views/cabling_add_servs/_form.html.erb
<%= form_for @additional_service do |f| %>
<div class="form-inline">
  <div class="form-group col-xs-12">
    <%= f.text_field :description, class: "form-control", placeholder: "Service Description" %>
  </div>
</div>
<%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/cabling_add_servs/edit.html.erb
<h2>Edit this Additional Cabling Service</h2>

<%= render 'form' %>

app/views/cabling_add_servs/new.html.erb
<div class="container">
<h2>Add New Additional Cabling Service</h2>

<%= render 'form' %>
</div>

app/views/cabling_services/_form.html.erb
<%= form_for @cabling_service do |f| %>
<div class="form-inline">
  <div class="form-group col-xs-12">
    <%= f.text_field :description, class: "form-control", placeholder: "Service Description" %>
  </div>
</div>
<%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/cabling_services/edit.html.erb
<div class="container">

<h2>Edit this Cabling Service</h2>

<%= render 'form' %>

</div>

app/views/cabling_services/index.html.erb
<div class="container" id="services-page">
<h1>Structured Cabling Services</h1>

<%= Addon.first.cabling_intro.html_safe %><br><br>

<ul class="col-xs-12">
  <% @cabling_services.each do |s| %>
  <li>
    <%= s.description %>
  </li>
<% end %>  
</ul>

<h1>Additional Structured Cabling Services</h1>
<ul class="col-xs-12">
  <% @additional_services.each do |as| %>
  <li>
    <%= as.description %>
  </li>
<% end %>
</ul>

<%= Addon.first.cabling_conclusion.html_safe %>

 <br><br>
    Respectfully,
    <br><br>
    <p>
      Joseph P. Feller<br>
      President<br>
      American Telecom West, Inc.<br>
      joe@americantelecomwest.com<br>
    </p>
</div>

app/views/cabling_services/new.html.erb
<div class="container">
<h2>Add a New Cabling Service</h2>

<%= render 'form' %>

</div>

app/views/clients/_form.html.erb
<%= form_for @client do |f| %>
<div class="form-inline">
  <div class="form-group col-xs-12">
    <%= f.text_field :name, class: "form-control", placeholder: "Client Name" %>
    <%= f.text_field :tag, class: "form-control", placeholder: "Client Tag Name" %>
    <%= f.text_field :logo_url, class: "form-control", placeholder: "Add path to the client's logo here" %>
  </div>
</div>
<%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/clients/edit.html.erb
<div class="container">

<h2>Edit this Client</h2>

<%= render 'form' %>
<div>

app/views/clients/index.html.erb
<div class="container" id="clients-page">
<h1>Satisfied Clients</h1>

<ul id="customer-list" class="clearfix center-block col-xs-12">
<% @clients.each do |c| %>
  <li class="col-sm-3 col-xs-6">
    <h3><%= c.name %></h3>
    <p><%= c.tag %></p>
     <img class="img-responsive" src="<%= c.logo_url %>">
  </li>
<% end %>
</ul>
</div>

app/views/clients/new.html.erb
<div class="container">
<h2>Add a New Client</h2>

<%= render 'form' %>
</div>

app/views/faqs/_form.html.erb
<%= form_for @faq do |f| %>
<div class="form-inline">
  <div class="form-group col-xs-12">
    <%= f.text_field :question, class: "form-control", placeholder: "Add the question here" %>
    <%= f.text_field :answer, class: "form-control", placeholder: "Add the answer here" %>
  </div>
</div>
<%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/faqs/edit.html.erb
<div class="container">

<h2>Edit this Frequently Asked Question</h2>
<%= render 'form' %>
</div>

app/views/faqs/index.html.erb
<div class="container" id="faq-page">
<h1>Frequently Asked Questions</h1>
<ul>
	<% @faqs.each do |faq| %>
  <li>
    <h3><%= faq.question %></h3>
    <p><%= faq.answer %></p>
  </li>
<% end %>
</ul %>

</div>

app/views/faqs/new.html.erb
<div class="container">
<h2>Add a New Frequently Asked Question</h2>

<%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmericanTelecomWest</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/top_nav' %>
  
  <div class="main-container clearfix">

    <% if flash[:notice] %>
    <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if flash[:alert] %>
    <p class="alert alert-warning"><%= alert %></p>
    <% end %>
    <% if flash[:error] %>
    <ul>
      <div class="alert alert-warning"><% flash[:error].each do |error| %>
        <li><%= error %></li>
        <% end %>
      </div>
    </ul>
    <% end %>

    <%= yield %>
  </div>
   <%= render 'shared/footer' %>
</body>
</html>

app/views/nortel_services/_form.html.erb
<%= form_for @nortel_service do |f| %>
<div class="form-inline">
  <div class="form-group col-xs-12">
    <%= f.text_field :description, class: "form-control", placeholder: "Service Description" %>
  </div>
</div>
<%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/nortel_services/edit.html.erb
<div class="container">

<h2>Edit this Nortel Service</h2>

<%= render 'form' %>

</div>

app/views/nortel_services/index.html.erb
<div class="container" id="services-page">
<h1>Nortel Legacy Solutions</h1>
<%= Addon.first.nortel_intro.html_safe %><br><br>

<ul class="col-xs-12">
  <% @nortel_services.each do |s| %>
  <li>
    <%= s.description %>
  </li>
<% end %>  
</ul>

<h1>Additional Nortel Legacy Solutions</h1>
<ul class="col-xs-12">
  <% @additional_services.each do |as| %>
  <li>
   <%= as.description %>
  </li>
<% end %>
</ul>

<%= Addon.first.nortel_conclusion.html_safe %><br><br>

 <br><br>
    Respectfully,
    <br><br>
    <p>
      Joseph P. Feller<br>
      President<br>
      American Telecom West, Inc.<br>
      joe@americantelecomwest.com<br>
    </p>
</div>

app/views/nortel_services/new.html.erb
<div class="container">
<h2>Add a New Nortel Service</h2>

<%= render 'form' %>

</div>

app/views/shared/_footer.html.erb
<footer>
<p>Contact us anytime at (800) 987-0010</p>
</footer>

app/views/shared/_top_nav.html.erb
<nav  role="navigation" class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a id="companyName" href="/" class="navbar-brand">
        <img src="/assets/ATW_logo.png">
      </a>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">
        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Services<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
              <li class="main"><%= link_to "Nortel Legacy Solutions", nortel_services_path, class: cp(nortel_services_path) %></li>
             <li class="main"><%= link_to "Structured Cabling", cabling_services_path, class: cp(cabling_services_path) %></li>
          </ul>
        </li>
        <li class="main"><%= link_to "Clients", clients_path, class: cp(clients_path) %></li>
        <li class="main"><%= link_to "FAQ", faqs_path, class: cp(faqs_path) %></li> 
           <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Partners <b class="caret"></b></a>
          <ul class="dropdown-menu">
        <li class="main"><%= link_to "T-Metrics", tmetrics_path, class: cp(tmetrics_path) %></li>
      </ul>
    </li>
        <%if user_signed_in? && is_admin? %>
        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Panel<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Admin Home", admin_path %></li>
            <li><%= link_to "Add Cabling Service", new_cabling_service_path %></li>
            <li><%= link_to "Add Additional Cabling Service", new_cabling_add_serv_path %></li>
            <li><%= link_to "Add Nortel Service", new_nortel_service_path %></li>
            <li><%= link_to "Add Additional Nortel Service", new_nortel_add_serv_path %></li>
            <li><%= link_to "Add Add On", new_addon_path %></li>
            <li><%= link_to "Add Clients", new_client_path %></li>
            <li><%= link_to "Add FAQ", new_faq_path %></li>
          </ul> 
        </li>
        <li class="main"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </ul>
  </div>
</div>
</nav>

app/views/static_pages/admin.html.erb
<div class="container" id="admin-page">
  <h1>Administrator's Page</h1>

  <div class="a-faq">
    <h2>Frequently Asked Questions <span><%= link_to "add another", new_faq_path %><span></h2>

    <ul>
      <% @faqs.each do |faq| %>
      <li class="col-sm-4">
        <h3><%= faq.question %></h3>
        <p><%= faq.answer %></p>
        <%= link_to "Delete", faq, method: :delete, class: "delete_link", remote: true %>
        <%= link_to "Edit", edit_faq_path(faq), class: "edit_link" %>
      </li>
      <% end %>
    </ul %>
  </div>

  <div class="addons">
    <h2>Intros and Conclusions <span><%= link_to "edit", edit_addon_path(@addon) %></span></h2>
    <ul>
      <li class="col-sm-12">
        <h3>Nortel Intro</h3>
        <p><%= @addon.nortel_intro %></p>
      </li>
      <li class="col-sm-12">
        <h3>Nortel Conclusion</h3>
        <p><%= @addon.nortel_conclusion %></p>
      </li>
      <li class="col-sm-12">
        <h3>Cabling Intro</h3>
        <p><%= @addon.cabling_intro %></p>
      </li>
      <li class="col-sm-12">
        <h3>Cabling Conclusion</h3>
        <p><%= @addon.cabling_conclusion %></p>
      </li>
    </ul %>
  </div>

  <div class="a-services">
    <h2>Nortel Services <span><%= link_to "add another", new_nortel_service_path %><span></h2>
    <ul>
      <% @nortel_services.each do |s| %>
      <li class="col-sm-4">
        <p><%= s.description %></p>
        <%= link_to "Delete", s, method: :delete, class: "delete_link", remote: true %>
        <%= link_to "Edit", edit_nortel_service_path(s), class: "edit_link" %>
      </li>
      <% end %>
    </ul %>
  </div>

  <div class="a-additional-services">
    <h2>Additional Nortel Services <span><%= link_to "add another", new_nortel_add_serv_path %><span></h2>
    <ul>
      <% @nortel_add_servs.each do |as| %>
      <li class="col-sm-4">
        <p><%= as.description %></p>
        <%= link_to "Delete", as, method: :delete, class: "delete_link", remote: true %>
        <%= link_to "Edit", edit_nortel_add_serv_path(as), class: "edit_link" %>
      </li>
      <% end %>
    </ul %>
  </div>

  <div class="a-services">
    <h2>Cabling Services <span><%= link_to "add another", new_cabling_service_path %><span></h2>
    <ul>
      <% @cabling_services.each do |s| %>
      <li class="col-sm-4">
        <p><%= s.description %></p>
        <%= link_to "Delete", s, method: :delete, class: "delete_link", remote: true %>
        <%= link_to "Edit", edit_cabling_service_path(s), class: "edit_link" %>
      </li>
      <% end %>
    </ul %>
  </div>

  <div class="a-additional-services">
    <h2>Additional Cabling Services <span><%= link_to "add another", new_cabling_add_serv_path %><span></h2>
    <ul>
      <% @cabling_add_servs.each do |as| %>
      <li class="col-sm-4">
        <p><%= as.description %></p>
        <%= link_to "Delete", as, method: :delete, class: "delete_link", remote: true %>
        <%= link_to "Edit", edit_cabling_add_serv_path(as), class: "edit_link" %>
      </li>
      <% end %>
    </ul %>
  </div>

  <div class="a-clients">
    <h2>Clients <span><%= link_to "add another", new_client_path %><span></h2>
    <ul>
      <% @clients.each do |c| %>
      <li class="col-sm-4">
        <h3><%= c.name %></h3>
        <p><%= c.tag %></p>
        <img src="<%= c.logo_url %>">
        <%= link_to "Delete", c, method: :delete, class: "delete_link", remote: true %>
        <%= link_to "Edit", edit_client_path(c), class: "edit_link" %>
      </li>
      <% end %>
    </ul %>
  </div>

</div>
   

app/views/static_pages/home.html.erb
<!-- <img id="home-hero" src="assets/homepageSlide.jpg" height="550"> -->
<div id="homepage-main" class="jumbotron">
	<div class="col-md-9 col-md-offset-2 home-main-div">
		<h1>American Telecom West</h1>
		<p>Working with you to design telecom solutions driven by your unique needs.</p>
		<h2>What are you interested in?</h2>
		<div id="home-buttons">
		<p class="col-sm-6 col-xs-12"><a href="/cabling_services" role="button" class="btn btn-primary btn-lg col-xs-12 col-md-10">Structured Cabling »</a></p>
		<p  class="col-sm-6  col-xs-12" style="float:right;"><a href="/nortel_services" role="button" class="btn btn-primary btn-lg  col-xs-12 col-md-10">Nortel Legacy Solutions »</a></p>
		</div>
	</div>
</div>

<div class="home-banner"><h3>Proudly partnered with </h3>
	<a href="/tmetrics"><img class="img-responsive" src="assets/tm_logo.gif" border="none" ></a>
</div>
<!-- Small modal -->
<div class="modal fade san-francisco-modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-body">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 class="modal-title" id="myModalLabel">San Francisco</h3>
				<div class="office-location">
					<h4>San Francisco Office</h4>
					<p>PO Box 1073
						<br>
						Benicia, CA 94510
					</p>
				</div>
				<div class="office-location">
					<h4>Joe</h4>
					<p><a href="mailto:joe@americantelecomwest.com">joe@americantelecomwest.com</a></p>
					<p>cell: (415) 902-3395</p>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /small modal -->
<!-- Small modal -->
<div class="modal fade boise-modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-body">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 class="modal-title" id="myModalLabel">Boise</h3>
				<div class="office-location">
					<h4>Boise Office</h4>
					<p>11832 W. Wilmont Street
						<br>
						Boise, ID 83709
					</p>
				</div>
				<div class="office-location">
					<h4>David</h4>
					<p><a href="mailto:david@boisenetworks.net">david@boisenetworks.net</a></p>
					<p>phone: (208) 863-6013</p>
					<p>fax: (208) 362-4049</p>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /small modal -->

<div id="homepage-sections" class="clearfix">
	<div class="col-sm-9 col-sm-offset-4"  data-toggle="modal" data-target=".san-francisco-modal">
		<img class="img-circle" src="assets/sf_thumb.jpg">
		<div class="col-sm-9">
			<h2>San Francisco</h2>
			<p><a role="button" class="btn btn-primary btn-lg">View Contact Info</a></p>
		</div>	
	</div>

	<div class="col-sm-9 col-sm-offset-4" data-toggle="modal" data-target=".boise-modal" style="margin-top:115px;">
		<img class="img-circle" src="assets/boise_thumb.jpg">
		<div class="col-sm-9">
			<h2>Boise</h2>
			<p><a role="button" class="btn btn-primary btn-lg">View Contact Info</a></p>
		</div>
	</div>
</div>

app/views/static_pages/tmetrics.html.erb
<div class="col-xs-12" id="tmetrics">
<h1>About T-Metrics</h1>
<br>
<div class="col-xs-12 col-sm-10">
 <img class="img-responsive" src="/assets/tm_logo.gif">
<p>
American Telecom West, Inc. is pleased to announce its partnership with T-Metrics in deploying Best of Breed solutions for your call handling requirements.
</p><p>
T-Metrics product lines fall into two major categories.  The first one is a cross platform Call Center solution.  While leveraging their alliance with Microsoft to provide customizable packages to suite all of your Call Center needs, T-Metrics also has decades of telephony experience which they have used to protect your legacy investments.  T-Metrics Call Center Solution is JITC Certified to operate in any DOD application and protect the security of your particular system.
</p><p>
In addition, T-Metrics has a second line of products known as Consolidated Operator Answering Systems (COAS).  For the first time, Call Center technology can be applied to your traditional operator environment.  T-Metrics has a superior solution over most “in skin” products because it can operate with whatever data bases you may have; both new and legacy.  The COAS solution is also a cross platform solution that allows you to keep the current operators locations while right sizing your staffing needs.
</p><p>
T-Metrics works with the premier brands of Telecommunications Manufacturers including Nortel, Avaya, and Cisco and others.  By working across a number of platforms, T-Metrics allows you to provide your users with robust and dynamic solutions while protecting your legacy investments.
</p><p>
<P>For more information <a href="/assets/T-Metrics-Glue.pdf" target="_blank">click here</a>.</p>
Please take the time to look at T-Metrics website at <a href="http://www.tmetrics.com/" target="_blank">www.tmetrics.com</a> or feel free to <a href="mailto:amtelwest@earthlink.net">contact me</a>.
</p>
<br><br>
Respectfully,
<br><br>
<p>
<strong>Joseph P. Feller</strong><br>
President, American Telecom West, Inc.<br>
<a href="mailto:joe@americantelecomwest.com">joe@americantelecomwest.com</a>
</p>
</div>
</div>